### ISSUE TITLE
Got errors when searching movies

### ISSUE THREAD

**Issue by monokoo** [MediaBrowser/Douban#1]
> 2019-08-08 02:17:38.011 Info HttpClient: GET https://api.douban.com/v2/movie/search?q=Zombieland.2009.BluRay.CEE.1080p.AVC.DTS-HD.MA.5.1-DiY@XXX&apikey=0dad551ec0f84ed02907ff5c42e8ec70
2019-08-08 02:17:38.149 Error App: Error in Douban
	*** Error Report ***
	Version: 4.2.0.40
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.4.59.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///system/System.Private.CoreLib.dll
	Processor count: 4
	Program data path: /config
	Application directory: /system
	System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
	   at Douban.DoubanMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
	Source: Douban
	TargetSite: Void MoveNext()

And the url link for searching movie got nothing. I think "searchInfo.Name" should be "Zombieland.2009".
Thanks

**Comment by LukePulverenti** [comment]
We pushed an update to the plugin to resolve this. Thanks.

**Comment by monokoo** [comment]
> We pushed an update to the plugin to resolve this. Thanks.
Cannot work as far now.

> 2019-08-16 05:04:10.441 Info HttpClient: GET https://api.douban.com/v2/movie/search?q=Badla (2019)&apikey=xxxx
2019-08-16 05:04:10.909 Info HttpClient: GET https://api.douban.com/v2/movie/subject/30254040?apikey=xxxx
2019-08-16 05:04:11.141 Error App: Error in Douban
	*** Error Report ***
	Version: 4.2.1.0
	Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
	Operating system: Unix 4.4.59.0
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///system/System.Private.CoreLib.dll
	Processor count: 4
	Program data path: /config
	Application directory: /system
	System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
	   at Douban.DoubanMovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
	Source: Douban
	TargetSite: Void MoveNext()

**Comment by LukePulverenti** [comment]
A new plugin update is headed up. thanks.
